import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";
import locationIds from "../location-ids.json";

/**
 * These tests guard the properties that make case-insensitive location
 * resolution safe. The list is generated by scripts/generate-location-ids.mjs
 * from public/eu-v-locations.svg; if the asset is refreshed without
 * regenerating, or regenerated from a drifted asset, these fail.
 */
describe("location-ids.json", () => {
  const ids = locationIds as readonly string[];

  it("carries one entry per path in the locations asset", () => {
    expect(ids.length).toBe(22711);
  });

  it("has no collisions when lowercased", () => {
    // Load-bearing: resolution keys on the lowercased name because saves emit
    // lowercase snake_case. A collision here would make resolution ambiguous.
    const lowered = new Set(ids.map((id) => id.toLowerCase()));
    expect(lowered.size).toBe(ids.length);
  });

  it("preserves lowercase particles that title-casing would destroy", () => {
    // 128 ids are not reproducible by per-segment title-casing. These are the
    // reason the list is stored rather than derived.
    expect(ids).toContain("Bar_le_Duc");
    expect(ids).toContain("Halle_an_der_Saale");
    expect(ids).toContain("Zell_am_See");
    expect(ids).not.toContain("Bar_Le_Duc");
    expect(ids).not.toContain("Halle_An_Der_Saale");
  });

  it("contains no empty or whitespace-bearing ids", () => {
    const malformed = ids.filter((id) => id === "" || /\s/.test(id));
    expect(malformed).toEqual([]);
  });

  it("matches the ids actually present in the committed asset", () => {
    const svg = readFileSync("public/eu-v-locations.svg", "utf8");
    const assetIds = new Set(
      [...svg.matchAll(/<path\s[^>]*id="([^"]+)"/g)].map((m) => m[1]),
    );
    const missing = ids.filter((id) => !assetIds.has(id));
    expect(missing).toEqual([]);
    expect(assetIds.size).toBe(ids.length);
  });
});
